/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simple_calculator;

/**
 *
 * @author YANGYANG_COMP111
 */
public class CalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorGUI
     */
    
    double Numberenter1, Numberenter2, Result;
    String Op;
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtxtResult = new javax.swing.JTextField();
        jbtnAllclear = new javax.swing.JButton();
        jbtnBackspace = new javax.swing.JButton();
        jbtnInteger = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jtbn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton0 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(76, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setBackground(new java.awt.Color(0, 153, 51));
        jtxtResult.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 320, 70));

        jbtnAllclear.setBackground(new java.awt.Color(153, 0, 0));
        jbtnAllclear.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtnAllclear.setText("AC");
        jbtnAllclear.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtnAllclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAllclearActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAllclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, 70));

        jbtnBackspace.setBackground(new java.awt.Color(153, 0, 0));
        jbtnBackspace.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jbtnBackspace.setText("←");
        jbtnBackspace.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 70));

        jbtnInteger.setBackground(new java.awt.Color(51, 51, 51));
        jbtnInteger.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtnInteger.setText("±");
        jbtnInteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIntegerActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInteger, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 80, 70));

        jbtnClear.setBackground(new java.awt.Color(153, 0, 0));
        jbtnClear.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtnClear.setText("C");
        jbtnClear.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 80, 70));

        jtbn7.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jtbn7.setText("7");
        jtbn7.setPreferredSize(new java.awt.Dimension(76, 0));
        jtbn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jtbn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, 70));

        jbtn8.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 80, 70));

        jbtn9.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 80, 70));

        jbtnPlus.setBackground(new java.awt.Color(51, 51, 51));
        jbtnPlus.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 80, 70));

        jbtn4.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, 70));

        jButton1.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButton1.setText("1");
        jButton1.setPreferredSize(new java.awt.Dimension(76, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 80, 70));

        jbtn5.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 80, 70));

        jButton2.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButton2.setText("2");
        jButton2.setPreferredSize(new java.awt.Dimension(76, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 80, 70));

        jbtn6.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setPreferredSize(new java.awt.Dimension(76, 0));
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 80, 70));

        jButton3.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButton3.setText("3");
        jButton3.setPreferredSize(new java.awt.Dimension(76, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 80, 70));

        jButtonMultiply.setBackground(new java.awt.Color(51, 51, 51));
        jButtonMultiply.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButtonMultiply.setText("x");
        jButtonMultiply.setPreferredSize(new java.awt.Dimension(76, 0));
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplyActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 80, 70));

        jButtonMinus.setBackground(new java.awt.Color(51, 51, 51));
        jButtonMinus.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.setPreferredSize(new java.awt.Dimension(76, 0));
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, 70));

        jLabel1.setFont(new java.awt.Font("Swis721 BdOul BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SIMPLE CALCULATOR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 270, 50));

        jButton0.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButton0.setText("0");
        jButton0.setPreferredSize(new java.awt.Dimension(76, 0));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 80, 70));

        jButtonDot.setBackground(new java.awt.Color(51, 51, 51));
        jButtonDot.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.setPreferredSize(new java.awt.Dimension(76, 0));
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 80, 70));

        jButtonEqual.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEqual.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.setPreferredSize(new java.awt.Dimension(76, 0));
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 80, 70));

        jButtonDivide.setBackground(new java.awt.Color(51, 51, 51));
        jButtonDivide.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jButtonDivide.setText("/");
        jButtonDivide.setPreferredSize(new java.awt.Dimension(76, 0));
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 80, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers(String q){
    String nums = jtxtResult.getText() + q;
    jtxtResult.setText(nums);
    }
    
    private void jbtnAllclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAllclearActionPerformed
        jtxtResult.setText("");
        
        String Fn, Sn;
        
        Fn = String.valueOf(Numberenter1);
        Sn = String.valueOf(Numberenter2);
        
        Fn = "";
        Sn = "";
        
        
    }//GEN-LAST:event_jbtnAllclearActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        if (! jtxtResult.getText().contains(".")) {
            jtxtResult.setText(jtxtResult.getText() + jButtonDot.getText());
        }
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        EnterNumbers("9");     
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        String Bs = null;
        if (jtxtResult.getText().length() > 0) {
            StringBuilder Sb = new StringBuilder(jtxtResult.getText());
            Sb.deleteCharAt(jtxtResult.getText().length() - 1); 
            Bs = Sb.toString();
            jtxtResult.setText(Bs);
        }
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jbtnIntegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIntegerActionPerformed
        double Integers = Double.parseDouble(String.valueOf(jtxtResult.getText()));
        Integers = Integers * (-1);
        jtxtResult.setText(String.valueOf(Integers));
    }//GEN-LAST:event_jbtnIntegerActionPerformed

    private void jtbn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_jtbn7ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        Numberenter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "/";
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplyActionPerformed
        Numberenter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "x";
    }//GEN-LAST:event_jButtonMultiplyActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        Numberenter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "-";
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        Numberenter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "+";
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jtxtResult.setText("");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        Numberenter2 = Double.parseDouble(jtxtResult.getText());
        if (Op == "+") {
            Result = Numberenter1 + Numberenter2;
            jtxtResult.setText(String.valueOf(Result));    
        }else  if (Op == "-") {
            Result = Numberenter1 - Numberenter2;
            jtxtResult.setText(String.valueOf(Result));
        }else  if (Op == "x") {
            Result = Numberenter1 * Numberenter2;
            jtxtResult.setText(String.valueOf(Result));
        }else  if (Op == "/") {
            Result = Numberenter1 / Numberenter2;
            jtxtResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAllclear;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnInteger;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jtbn7;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
